# Generated by Django 5.0.6 on 2024-07-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_book', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection_app.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection_app.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.ManyToManyField(through='connection_app.BookPrice', to='connection_app.publisher'),
        ),
    ]
